# Generated by Django 4.2.13 on 2024-05-27 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frases', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autor',
            options={'verbose_name_plural': 'Autores'},
        ),
    ]
